### ISSUE TITLE
Move get_args code to if main:

### ISSUE THREAD

**Issue by LeeBergstrand** [qsirianni/ipa#1]

**Comment by qsirianni** [comment]
I considered placing the **get_args** code in either the **main** function or **if main** statement but I decided not to for a couple of reasons. First, I find it easier to read the code if each action the code performs is enclosed in a function (even if that function is only called once). The separation of discrete ideas and actions helps with maintenance of the code later on. Secondly, encapsulating the **get_args** code in a function allows the _parser_ variable to be cleaned up after it is no longer needed. Placing the _parser_ in **main** or **if main** keeps the variable around for the entire runtime for no reason.

Overall, it's a style choice whether or not to place the **get_args** code in a function. I like the way it is now.

**Comment by qsirianni** [comment]
I changed the code as you suggested. I have to admit it makes more sense this way now that I've seen the comparison. As a bonus, I can now conditionally import argparse (dunno why, but this makes me happy)
